### ISSUE TITLE
Qur'an pages not shown

### ISSUE THREAD

**Issue by jaxongir** [DBChoco/Muezzin#10]
Assalamu Alaykum!

Thanks for the app, but I have one issue with it. It doesn't show Qur'an's sura. Does it download Qur'an files from the web? If yes, I think the resource may be blocked by our government. 

OS: ArchLinux

![image](https://user-images.githubusercontent.com/7779212/163519520-c9c5d25f-75ad-4b0c-aa85-21715e5608e3.png)

**Comment by DBChoco** [comment]
Wa Alaykoum Assalamou brother/sister.
The Qur'an is indeed loaded from the internet, I use Quran.com API for the verses.
Could you try to load this: https://api.quran.com/api/v4/verses/by_chapter/1?language=en&words=true&page=1&per_page=10 ?
Could you also try to load the Surah with developer tools On so that I can see if there are any error messages ? You can toggle them on by pressing alt, then on the menu "Debug" => "Toggle Developer Tools"

Jazzaka Lahu khairan.

**Comment by jaxongir** [comment]
Thanks for your fast reply.

I tried what you asked. Unfortunately, Quran.com is blocked in Uzbekistan. It is opened only via vpn.

![image](https://user-images.githubusercontent.com/7779212/163552853-92487a56-2ab6-4a16-85fc-622880edde63.png)

**Comment by DBChoco** [comment]
That's really unfortunate, I'll perhaps add offline support (only arabic) someday inshaAllah, would you be interested in that ?
It might add to the app size though

**Comment by DBChoco** [comment]
Just looked it up, it's only 1.4Mb so inshaAllah I'll add it next update, this I'll close this for now.
If you need anything feel free to contact me again.
Assalamou Alaykoum wa Rahmatou Lahi wa Baraketu!

**Comment by DBChoco** [comment]
Assalamou Alaykoum!
https://github.com/DBChoco/Muezzin/commit/5bb8484f8f464769e8cb08ab54f043e258fe5ccc
Here it is, I'll be availible next update inshaAllah.

**Comment by jaxongir** [comment]
Wa alaykoum assalam!

Thank you brother.
