### ISSUE TITLE
Flatpak version does not have autostart | Suggestion for tray icon

### ISSUE THREAD

**Issue by snocodile** [DBChoco/Muezzin#17]
Salaam alaykum,

I've discovered Muezzin through Flathub while looking for a prayer app.

I have to say it is probably the best open source prayer app for desktops right now, you're a skilled developer!

I'd like to add a very minor thing for autostart on Linux for the Flathub version. It is missing the corresponding autostart entry in the config folder of the user **[$HOME/.config/autostart/io.github.dbchoco.muezzin.desktop]**, which I quickly just put there myself. It would have to look like this:

> [Desktop Entry]
> Type=Application
> Name=Muezzin
> Exec=flatpak run io.github.dbchoco.muezzin --background --start-in-traysy
> Comment=Muezzin startup

Without this entry in the autostart folder the flatpak app won't start up when booting even if you have selected the corresponding options (autostart, start to tray) in the Muezzin app.

Furthermore I've suggestions for the system tray icon. It'd be great if it was possible to toggle closing the app to tray while (double-) clicking the tray icon. That's currently not possible for me and right clicking "quit" on the context menu kills the app unfortunately, when I just want to minimize the window into tray. It would also be great if there would be monochromatic icons since that would fit better into some people's icon theming.

Thanks for all your work. JazakAllahu Khairan.

**Comment by DBChoco** [comment]
Wa Alaykoum Assalam wa Rahmatou Lahi wa Baraketu !

First and foremost, Jazzaka Lahu khairan for all the compliments, I truly appreciate it !

About the Autostart, I didn't notice it before but as you have said, on Linux, the autostart feature doesn't work. It's quite complicated because you can install the app many ways (flatpak, snapcraft, appimage, aur, and others). So defining a .desktop file that could work with all of them might be very difficult, at least I don't see how to do it for now. For now it's easier if I let the users set the app to start at launch by using their own Desktop Environments. 

I'm very sorry if I can't find a solution, you said I was a skilled developer but I might have to disagree on this hahaha

The suggestion about the double click on the tray icon to open the app is a really nice one Tabaraka Allahu, I'll keep this issue open and InshaAllah when I get the time I'll do it brother/sister. I don't have much time, but inshaAllah when I get some time I'll do it. Making the tray icon black and white is also a very good idea, I don't know how to do it though, I'm not skilled at all in design, so I won't promise anything, but I'll try inshaAllah!

Thank you as well for your sweet messages and compliments. Wa Iyakum, Jazzakoum Allahu khairan.

**Comment by DBChoco** [comment]
Assalam Alaykoum brother/sister, 
Sorry for the delay, I've looked into your 2 propositions and here is what came up:

1. Adding a universal auto-start on Flathub for all distributions is quite difficult to do, what is usually done is simply to use one own DE to start the application automatically on startup.
2. Adding a double click event to the tray icon for Electron apps is not yet implemented properly. I could use some workarounds, but I don't want provoke delays and problems by doing that.

Sorry for the fruitless wait, I've been really busy this past year. With all of this being said, I wish you and all of the Muslims around the world a Blessed Ramadan. Let's keep doing our best inshaAllah and Assalam Alaykoum wa Rahmatou Lahi wa Baraketu.
