### ISSUE TITLE
Feature request: Provide new icon theme

### ISSUE THREAD

**Issue by hydroEng** [DBChoco/Muezzin#18]
As-Salaamu Alaykum,

Thanks for the great application.

Would it be possible to provide a new tray icon theme that integrates better with KDE or GNOME? Or at least the option to select the tray icon. The current icon seems kind of blurry and stands out against the black / white KDE or GNOME tray icons. See KDE HIG:

https://develop.kde.org/hig/style/icons/monochrome/

I know this is a really low priority request, but it would make this app integrate really well.

![image](https://user-images.githubusercontent.com/59785388/209676584-eafaa0c5-bc7f-46d7-9823-32b32fdeb76c.png)

**Comment by DBChoco** [comment]
Wa Alaykoum Assalam wa Rahmatou Lahi wa Baraketu akhi
I'll add it as a suggestion, I'll inshaAllah try to do it in the upcoming months inshaAllah.
Jazzaka Lahu khairan for the idea.

**Comment by DBChoco** [comment]
Assalam Alaykoum brother, I wanted to ask you which one you preferred:
![image](https://user-images.githubusercontent.com/44785461/229276061-5eaafb30-9742-456a-a75a-7c0e9d49bd4c.png)

**Comment by bakrtech** [comment]
walikumasalam brother is there any way we can select from the two during time of launch on linux

**Comment by hydroEng** [comment]
@DBChoco Personally I think the black and white one looks best, since it blends in with the KDe / gnome icons.

**Comment by bakrtech** [comment]
so how to use that 
if yes please push it in the next update

**Comment by DBChoco** [comment]
> walikumasalam brother is there any way we can select from the two during time of launch on linux

@bakrtech Doing this would be quite difficult, which one do you prefer, the color version or the grey one ?
If you really insist on having both I could make it but it'd take a while longer, especially since I'm a bit busy.

**Comment by DBChoco** [comment]
I've asked some brothers and they told me they prefer the color version, so I really don't know how to proceed with this issue haha

**Comment by bakrtech** [comment]
Ok that feels ok to me proceed and close this issue

**Comment by hydroEng** [comment]
Happy with coloured if everyone else wants that :)

**Comment by DBChoco** [comment]
Okay brothers, so for now I'll keep it this way. Sorry if this disappoints you in any way, shape or form. I thought about giving the user a choice, but it unfortunately I don't have much time these days and it doesn't seem like a critical issue to me
I'll put the grey icon here so that if any person wants to build it from source, they can do so easily.

Jazzakoum Allahu khairan for the suggestions and help, it is really nice to see people using the app and discussing it.
I wish you a blessed Ramadan, may Allah allow us to make the best out of these 10 days and nights.

Assalam Alaykoum wa Rahmatou Lahi wa Baraketu !

![icon](https://user-images.githubusercontent.com/44785461/230734886-cc91fb51-e916-4486-9006-75b995af58ba.png)
