### ISSUE TITLE
Update to 2.6.0

### ISSUE THREAD

**Issue by DBChoco** [DBChoco/Muezzin#30]
Enough changes and updates, as soon as I get free time I'll begin all the update operations.

**Comment by DBChoco** [comment]
Sorry for the delay, terribly busy, expect 1 or 2 more months inshaAllah

**Comment by MisconceivedSec** [comment]
السلام عليكم و رحمة الله و بركاته
May Allah reward you for this excellent application, ما شاء الله

I would like to share some feedback (my initial thoughts, just installed it):
- I think using a monospace font for the changing time text would be better. Because using a non-monospace font causes the text box to change size almost every second and it doesn't look too good.
- And maybe add a toggle button for the Hijri/Gregorian date text box, rather then it alternating between them?


جزاكم الله كل خير

**Comment by DBChoco** [comment]
Wa Alaykoum Assalam wa Rahmatou Lahi wa Baraketu, sorry for not replying, seems like I just went through the notifications without paying attention.

I'll take your suggestion into account inshaAllah, but I'll create another issue for that.
Wa Iyakum !

Assalam Alaykoum wa Rahmatou Lahi wa Baraketu.
