### ISSUE TITLE
Adhan Setting Keeps Changing Back

### ISSUE THREAD

**Issue by EternalTranquility1** [DBChoco/Muezzin#45]
As-salamu alaykum
I have the newest version of the app '2.6.0' on Windows 10 'Version 10.0.19044 Build 19044.' I'm trying to choose the 'Short sound - Mishary Rashid Alafasy' for the Adhan, but it keeps going back to 'Adhan - Ahmed Al-Nufais.'
![UGWMuJvSqS](https://github.com/DBChoco/Muezzin/assets/50317210/aef3dd1b-9a81-4265-9abd-e773def164a2)

**Comment by DBChoco** [comment]
Wa Alaykoum Assalam wa Rahmatou Lahi wa Baraketu !

Baraka Lahu feek, it should be fixed with this inshaAllah: https://github.com/DBChoco/Muezzin/commit/8c1bd109ffee5a06067e97383d7866bdca159849

It might be some time before I push the update though; in the meanwhile, here's how to work around it;
choose the adhan you like, and then don't go to the settings again; the adhan is saved, it's only after you go back to the settings that the app fails to read the adhan that you chose before, so it gives you the default one.
You can also chose a custom one without any problem inshaAllah.

**Comment by staaandup** [comment]
Jazak Allaahu khayran
